repos:
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.24.4
    hooks:
      - id: latexindent
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: "v0.21.0"
    hooks:
      - id: yamlfmt
  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat --wrap 120
        language: python
        types: [markdown]
        additional_dependencies:
          - mdformat-gfm>=1
          - mdformat-ruff>=0.1.3
