name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"
jobs:
  build:
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - name: 🛎️ Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 📕 Compile LaTeX document 📕
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # 4.1.0
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cv
          path: main.pdf
  deploy:
    runs-on: ubuntu-26.04
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    environment:
      name: release
      url: https://gaborbernat.github.io/cv/main.pdf
    permissions:
      contents: write
    steps:
      - name: 🛎️ Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cv
          path: built
      - name: 🚀 Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          folder: built
          single-commit: true
